#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKActiveDirectoryXMLIngestApi' {
    Context 'ConvertTo-OKgestXML' {
        It 'Test ConvertTo-OKgestXML' {
            #$TestResult = ConvertTo-OKgestXML -Version "TEST_VALUE" -WriteLayerID "TEST_VALUE" -SearchLayerIDs "TEST_VALUE" -Files "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
