#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKAnsibleInventoryScanIngestApi' {
    Context 'ConvertTo-OKgestAnsibleInventoryScan' {
        It 'Test ConvertTo-OKgestAnsibleInventoryScan' {
            #$TestResult = ConvertTo-OKgestAnsibleInventoryScan -WriteLayerID "TEST_VALUE" -SearchLayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AnsibleInventoryScanDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
