#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKAttributeValueImageApi' {
    Context 'Get-OK' {
        It 'Test Get-OK' {
            #$TestResult = Get-OK -Ciid "TEST_VALUE" -AttributeName "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -Index "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-OK' {
        It 'Test Submit-OK' {
            #$TestResult = Submit-OK -Ciid "TEST_VALUE" -AttributeName "TEST_VALUE" -LayerID "TEST_VALUE" -Version "TEST_VALUE" -Files "TEST_VALUE" -ForceArray "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
