#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKAttributeApi' {
    Context 'Invoke-OKBulkReplaceAttributesInLayer' {
        It 'Test Invoke-OKBulkReplaceAttributesInLayer' {
            #$TestResult = Invoke-OKBulkReplaceAttributesInLayer -Version "TEST_VALUE" -BulkCIAttributeLayerScopeDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Find-OKMergedAttributesByName' {
        It 'Test Find-OKMergedAttributesByName' {
            #$TestResult = Find-OKMergedAttributesByName -Regex "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -Ciids "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedAttribute' {
        It 'Test Get-OKMergedAttribute' {
            #$TestResult = Get-OKMergedAttribute -Ciid "TEST_VALUE" -Name "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedAttributes' {
        It 'Test Get-OKMergedAttributes' {
            #$TestResult = Get-OKMergedAttributes -Ciids "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedAttributesWithName' {
        It 'Test Get-OKMergedAttributesWithName' {
            #$TestResult = Get-OKMergedAttributesWithName -Name "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
