#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKAuthRedirectApi' {
    Context 'Invoke-OKAuthRedirectIndex' {
        It 'Test Invoke-OKAuthRedirectIndex' {
            #$TestResult = Invoke-OKAuthRedirectIndex
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
