#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKCISearchApi' {
    Context 'Search-OKCIsByTraits' {
        It 'Test Search-OKCIsByTraits' {
            #$TestResult = Search-OKCIsByTraits -LayerIDs "TEST_VALUE" -WithTraits "TEST_VALUE" -WithoutTraits "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
