#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKCIApi' {
    Context 'Get-OKAllCIIDs' {
        It 'Test Get-OKAllCIIDs' {
            #$TestResult = Get-OKAllCIIDs -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKCIByID' {
        It 'Test Get-OKCIByID' {
            #$TestResult = Get-OKCIByID -LayerIDs "TEST_VALUE" -CIID "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKCIsByID' {
        It 'Test Get-OKCIsByID' {
            #$TestResult = Get-OKCIsByID -LayerIDs "TEST_VALUE" -CIIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
