#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKCytoscapeApi' {
    Context 'Invoke-OKCytoscapeTraitCentric' {
        It 'Test Invoke-OKCytoscapeTraitCentric' {
            #$TestResult = Invoke-OKCytoscapeTraitCentric -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -TraitIDs "TEST_VALUE" -TraitIDsRegex "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
