#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKGraphQLApi' {
    Context 'Debug-OK' {
        It 'Test Debug-OK' {
            #$TestResult = Debug-OK -GraphQLQuery "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-OKdex' {
        It 'Test ConvertTo-OKdex' {
            #$TestResult = ConvertTo-OKdex -GraphQLQuery "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
