#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKGraphvizDotApi' {
    Context 'Invoke-OKGraphvizDotLayerCentric' {
        It 'Test Invoke-OKGraphvizDotLayerCentric' {
            #$TestResult = Invoke-OKGraphvizDotLayerCentric -LayerIDs "TEST_VALUE" -From "TEST_VALUE" -To "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-OKGraphvizDotTraitCentric' {
        It 'Test Invoke-OKGraphvizDotTraitCentric' {
            #$TestResult = Invoke-OKGraphvizDotTraitCentric -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -TraitIDs "TEST_VALUE" -TraitIDsRegex "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
