#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKLayerApi' {
    Context 'Get-OKAllLayers' {
        It 'Test Get-OKAllLayers' {
            #$TestResult = Get-OKAllLayers -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKLayerByName' {
        It 'Test Get-OKLayerByName' {
            #$TestResult = Get-OKLayerByName -LayerName "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKLayersByName' {
        It 'Test Get-OKLayersByName' {
            #$TestResult = Get-OKLayersByName -LayerNames "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
