#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKMetadataApi' {
    Context 'Invoke-OKMetadataGetMetadata' {
        It 'Test Invoke-OKMetadataGetMetadata' {
            #$TestResult = Invoke-OKMetadataGetMetadata -Context "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-OKMetadataGetServiceDocument' {
        It 'Test Invoke-OKMetadataGetServiceDocument' {
            #$TestResult = Invoke-OKMetadataGetServiceDocument -Context "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
