#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKOKPluginInsightDiscoveryIngestApi' {
    Context 'ConvertTo-OKgestFileIngest' {
        It 'Test ConvertTo-OKgestFileIngest' {
            #$TestResult = ConvertTo-OKgestFileIngest -Context "TEST_VALUE" -Version "TEST_VALUE" -ContentType "TEST_VALUE" -ContentDisposition "TEST_VALUE" -Length "TEST_VALUE" -Name "TEST_VALUE" -FileName "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
