#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKRelationApi' {
    Context 'Get-OKAllMergedRelations' {
        It 'Test Get-OKAllMergedRelations' {
            #$TestResult = Get-OKAllMergedRelations -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedRelation' {
        It 'Test Get-OKMergedRelation' {
            #$TestResult = Get-OKMergedRelation -FromCIID "TEST_VALUE" -ToCIID "TEST_VALUE" -PredicateID "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedRelationsFromOrToCI' {
        It 'Test Get-OKMergedRelationsFromOrToCI' {
            #$TestResult = Get-OKMergedRelationsFromOrToCI -Ciid "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedRelationsOutgoingFromCI' {
        It 'Test Get-OKMergedRelationsOutgoingFromCI' {
            #$TestResult = Get-OKMergedRelationsOutgoingFromCI -FromCIID "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OKMergedRelationsWithPredicate' {
        It 'Test Get-OKMergedRelationsWithPredicate' {
            #$TestResult = Get-OKMergedRelationsWithPredicate -PredicateID "TEST_VALUE" -LayerIDs "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
