#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKRestartApplicationApi' {
    Context 'Restart-OKApplicationRestart' {
        It 'Test Restart-OKApplicationRestart' {
            #$TestResult = Restart-OKApplicationRestart -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
