#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKTraitApi' {
    Context 'Get-OKEffectiveTraitsForTraitName' {
        It 'Test Get-OKEffectiveTraitsForTraitName' {
            #$TestResult = Get-OKEffectiveTraitsForTraitName -LayerIDs "TEST_VALUE" -TraitName "TEST_VALUE" -Version "TEST_VALUE" -AtTime "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
