#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKOKUsageStatsApi' {
    Context 'Invoke-OKUsageStatsFetch' {
        It 'Test Invoke-OKUsageStatsFetch' {
            #$TestResult = Invoke-OKUsageStatsFetch -From "TEST_VALUE" -To "TEST_VALUE" -Version "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
