#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKAttributeValueDTO' {
    Context 'OKAttributeValueDTO' {
        It 'Initialize-OKAttributeValueDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKAttributeValueDTO -Type "TEST_VALUE" -IsArray "TEST_VALUE" -Values "TEST_VALUE"
            #$NewObject | Should -BeOfType AttributeValueDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
