#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKAttributeValueType' {
    Context 'OKAttributeValueType' {
        It 'Initialize-OKAttributeValueType' {
            # a simple test to create an object
            #$NewObject = Initialize-OKAttributeValueType
            #$NewObject | Should -BeOfType AttributeValueType
            #$NewObject.property | Should -Be 0
        }
    }
}
