#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKAttributeState' {
    Context 'OKAttributeState' {
        It 'Initialize-OKAttributeState' {
            # a simple test to create an object
            #$NewObject = Initialize-OKAttributeState
            #$NewObject | Should -BeOfType AttributeState
            #$NewObject.property | Should -Be 0
        }
    }
}
