#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKChangeDataRequest' {
    Context 'OKChangeDataRequest' {
        It 'Initialize-OKChangeDataRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-OKChangeDataRequest -SparseRows "TEST_VALUE"
            #$NewObject | Should -BeOfType ChangeDataRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
