#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKCIAttributeDTO' {
    Context 'OKCIAttributeDTO' {
        It 'Initialize-OKCIAttributeDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKCIAttributeDTO -Id "TEST_VALUE" -Name "TEST_VALUE" -Value "TEST_VALUE" -Ciid "TEST_VALUE" -State "TEST_VALUE"
            #$NewObject | Should -BeOfType CIAttributeDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
