#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKContext' {
    Context 'OKContext' {
        It 'Initialize-OKContext' {
            # a simple test to create an object
            #$NewObject = Initialize-OKContext -Name "TEST_VALUE" -ExtractConfig "TEST_VALUE" -TransformConfig "TEST_VALUE" -LoadConfig "TEST_VALUE"
            #$NewObject | Should -BeOfType Context
            #$NewObject.property | Should -Be 0
        }
    }
}
