#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEditContextRequest' {
    Context 'OKEditContextRequest' {
        It 'Initialize-OKEditContextRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEditContextRequest -SpeakingName "TEST_VALUE" -Description "TEST_VALUE" -Configuration "TEST_VALUE"
            #$NewObject | Should -BeOfType EditContextRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
