#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEdmContainerElementKind' {
    Context 'OKEdmContainerElementKind' {
        It 'Initialize-OKEdmContainerElementKind' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEdmContainerElementKind
            #$NewObject | Should -BeOfType EdmContainerElementKind
            #$NewObject.property | Should -Be 0
        }
    }
}
