#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEdmExpressionKind' {
    Context 'OKEdmExpressionKind' {
        It 'Initialize-OKEdmExpressionKind' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEdmExpressionKind
            #$NewObject | Should -BeOfType EdmExpressionKind
            #$NewObject.property | Should -Be 0
        }
    }
}
