#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEdmSchemaElementKind' {
    Context 'OKEdmSchemaElementKind' {
        It 'Initialize-OKEdmSchemaElementKind' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEdmSchemaElementKind
            #$NewObject | Should -BeOfType EdmSchemaElementKind
            #$NewObject.property | Should -Be 0
        }
    }
}
