#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEdmTypeKind' {
    Context 'OKEdmTypeKind' {
        It 'Initialize-OKEdmTypeKind' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEdmTypeKind
            #$NewObject | Should -BeOfType EdmTypeKind
            #$NewObject.property | Should -Be 0
        }
    }
}
