#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKEffectiveTraitDTO' {
    Context 'OKEffectiveTraitDTO' {
        It 'Initialize-OKEffectiveTraitDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKEffectiveTraitDTO -TraitAttributes "TEST_VALUE" -TraitRelations "TEST_VALUE"
            #$NewObject | Should -BeOfType EffectiveTraitDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
