#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKFragmentDTO' {
    Context 'OKFragmentDTO' {
        It 'Initialize-OKFragmentDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKFragmentDTO -Name "TEST_VALUE" -Value "TEST_VALUE" -Ciid "TEST_VALUE"
            #$NewObject | Should -BeOfType FragmentDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
