#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGenericInboundRelation' {
    Context 'OKGenericInboundRelation' {
        It 'Initialize-OKGenericInboundRelation' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGenericInboundRelation -VarFrom "TEST_VALUE" -Predicate "TEST_VALUE" -To "TEST_VALUE"
            #$NewObject | Should -BeOfType GenericInboundRelation
            #$NewObject.property | Should -Be 0
        }
    }
}
