#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGenericInboundAttribute' {
    Context 'OKGenericInboundAttribute' {
        It 'Initialize-OKGenericInboundAttribute' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGenericInboundAttribute -Name "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType GenericInboundAttribute
            #$NewObject.property | Should -Be 0
        }
    }
}
