#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGenericInboundCI' {
    Context 'OKGenericInboundCI' {
        It 'Initialize-OKGenericInboundCI' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGenericInboundCI -TempID "TEST_VALUE" -IdMethod "TEST_VALUE" -SameTempIDHandling "TEST_VALUE" -SameTargetCIHandling "TEST_VALUE" -NoFoundTargetCIHandling "TEST_VALUE" -Attributes "TEST_VALUE"
            #$NewObject | Should -BeOfType GenericInboundCI
            #$NewObject.property | Should -Be 0
        }
    }
}
