#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGenericInboundData' {
    Context 'OKGenericInboundData' {
        It 'Initialize-OKGenericInboundData' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGenericInboundData -Cis "TEST_VALUE" -Relations "TEST_VALUE"
            #$NewObject | Should -BeOfType GenericInboundData
            #$NewObject.property | Should -Be 0
        }
    }
}
