#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGridViewConfiguration' {
    Context 'OKGridViewConfiguration' {
        It 'Initialize-OKGridViewConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGridViewConfiguration -ShowCIIDColumn "TEST_VALUE" -WriteLayer "TEST_VALUE" -ReadLayerset "TEST_VALUE" -Columns "TEST_VALUE" -Trait "TEST_VALUE"
            #$NewObject | Should -BeOfType GridViewConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
