#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKGridViewColumn' {
    Context 'OKGridViewColumn' {
        It 'Initialize-OKGridViewColumn' {
            # a simple test to create an object
            #$NewObject = Initialize-OKGridViewColumn -SourceAttributeName "TEST_VALUE" -ColumnDescription "TEST_VALUE" -ValueType "TEST_VALUE" -WriteLayer "TEST_VALUE"
            #$NewObject | Should -BeOfType GridViewColumn
            #$NewObject.property | Should -Be 0
        }
    }
}
