#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIAttributeValue' {
    Context 'OKIAttributeValue' {
        It 'Initialize-OKIAttributeValue' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIAttributeValue -Type "TEST_VALUE" -IsArray "TEST_VALUE"
            #$NewObject | Should -BeOfType IAttributeValue
            #$NewObject.property | Should -Be 0
        }
    }
}
