#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmExpression' {
    Context 'OKIEdmExpression' {
        It 'Initialize-OKIEdmExpression' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmExpression -ExpressionKind "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmExpression
            #$NewObject.property | Should -Be 0
        }
    }
}
