#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmEntityContainer' {
    Context 'OKIEdmEntityContainer' {
        It 'Initialize-OKIEdmEntityContainer' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmEntityContainer -Elements "TEST_VALUE" -SchemaElementKind "TEST_VALUE" -Namespace "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmEntityContainer
            #$NewObject.property | Should -Be 0
        }
    }
}
