#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmEntityContainerElement' {
    Context 'OKIEdmEntityContainerElement' {
        It 'Initialize-OKIEdmEntityContainerElement' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmEntityContainerElement -ContainerElementKind "TEST_VALUE" -Container "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmEntityContainerElement
            #$NewObject.property | Should -Be 0
        }
    }
}
