#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmModel' {
    Context 'OKIEdmModel' {
        It 'Initialize-OKIEdmModel' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmModel -SchemaElements "TEST_VALUE" -VocabularyAnnotations "TEST_VALUE" -ReferencedModels "TEST_VALUE" -DeclaredNamespaces "TEST_VALUE" -DirectValueAnnotationsManager "TEST_VALUE" -EntityContainer "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmModel
            #$NewObject.property | Should -Be 0
        }
    }
}
