#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmVocabularyAnnotation' {
    Context 'OKIEdmVocabularyAnnotation' {
        It 'Initialize-OKIEdmVocabularyAnnotation' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmVocabularyAnnotation -Qualifier "TEST_VALUE" -Term "TEST_VALUE" -Target "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmVocabularyAnnotation
            #$NewObject.property | Should -Be 0
        }
    }
}
