#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKIEdmTypeReference' {
    Context 'OKIEdmTypeReference' {
        It 'Initialize-OKIEdmTypeReference' {
            # a simple test to create an object
            #$NewObject = Initialize-OKIEdmTypeReference -IsNullable "TEST_VALUE" -Definition "TEST_VALUE"
            #$NewObject | Should -BeOfType IEdmTypeReference
            #$NewObject.property | Should -Be 0
        }
    }
}
