#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKILoadConfig' {
    Context 'OKILoadConfig' {
        It 'Initialize-OKILoadConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-OKILoadConfig -SearchLayerIDs "TEST_VALUE" -WriteLayerID "TEST_VALUE"
            #$NewObject | Should -BeOfType ILoadConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
