#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKInboundIDMethodByIntersect' {
    Context 'OKInboundIDMethodByIntersect' {
        It 'Initialize-OKInboundIDMethodByIntersect' {
            # a simple test to create an object
            #$NewObject = Initialize-OKInboundIDMethodByIntersect -Type "TEST_VALUE" -Inner "TEST_VALUE"
            #$NewObject | Should -BeOfType InboundIDMethodByIntersect
            #$NewObject.property | Should -Be 0
        }
    }
}
