#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKInboundIDMethodByTemporaryCIID' {
    Context 'OKInboundIDMethodByTemporaryCIID' {
        It 'Initialize-OKInboundIDMethodByTemporaryCIID' {
            # a simple test to create an object
            #$NewObject = Initialize-OKInboundIDMethodByTemporaryCIID -Type "TEST_VALUE" -TempID "TEST_VALUE"
            #$NewObject | Should -BeOfType InboundIDMethodByTemporaryCIID
            #$NewObject.property | Should -Be 0
        }
    }
}
