#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKInboundIDMethodByRelatedTempID' {
    Context 'OKInboundIDMethodByRelatedTempID' {
        It 'Initialize-OKInboundIDMethodByRelatedTempID' {
            # a simple test to create an object
            #$NewObject = Initialize-OKInboundIDMethodByRelatedTempID -Type "TEST_VALUE" -TempID "TEST_VALUE" -OutgoingRelation "TEST_VALUE" -PredicateID "TEST_VALUE"
            #$NewObject | Should -BeOfType InboundIDMethodByRelatedTempID
            #$NewObject.property | Should -Be 0
        }
    }
}
