#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKInboundIDMethodByData' {
    Context 'OKInboundIDMethodByData' {
        It 'Initialize-OKInboundIDMethodByData' {
            # a simple test to create an object
            #$NewObject = Initialize-OKInboundIDMethodByData -Type "TEST_VALUE" -Attributes "TEST_VALUE"
            #$NewObject | Should -BeOfType InboundIDMethodByData
            #$NewObject.property | Should -Be 0
        }
    }
}
