#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKNoFoundTargetCIHandling' {
    Context 'OKNoFoundTargetCIHandling' {
        It 'Initialize-OKNoFoundTargetCIHandling' {
            # a simple test to create an object
            #$NewObject = Initialize-OKNoFoundTargetCIHandling
            #$NewObject | Should -BeOfType NoFoundTargetCIHandling
            #$NewObject.property | Should -Be 0
        }
    }
}
