#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKODataTypeAnnotation' {
    Context 'OKODataTypeAnnotation' {
        It 'Initialize-OKODataTypeAnnotation' {
            # a simple test to create an object
            #$NewObject = Initialize-OKODataTypeAnnotation -TypeName "TEST_VALUE"
            #$NewObject | Should -BeOfType ODataTypeAnnotation
            #$NewObject.property | Should -Be 0
        }
    }
}
