#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKODataServiceDocument' {
    Context 'OKODataServiceDocument' {
        It 'Initialize-OKODataServiceDocument' {
            # a simple test to create an object
            #$NewObject = Initialize-OKODataServiceDocument -TypeAnnotation "TEST_VALUE" -EntitySets "TEST_VALUE" -Singletons "TEST_VALUE" -FunctionImports "TEST_VALUE"
            #$NewObject | Should -BeOfType ODataServiceDocument
            #$NewObject.property | Should -Be 0
        }
    }
}
