#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKODataSingletonInfo' {
    Context 'OKODataSingletonInfo' {
        It 'Initialize-OKODataSingletonInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-OKODataSingletonInfo -TypeAnnotation "TEST_VALUE" -Url "TEST_VALUE" -Name "TEST_VALUE" -Title "TEST_VALUE"
            #$NewObject | Should -BeOfType ODataSingletonInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
