#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKPredicateDTO' {
    Context 'OKPredicateDTO' {
        It 'Initialize-OKPredicateDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKPredicateDTO -Id "TEST_VALUE" -WordingFrom "TEST_VALUE" -WordingTo "TEST_VALUE"
            #$NewObject | Should -BeOfType PredicateDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
