#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKRelationState' {
    Context 'OKRelationState' {
        It 'Initialize-OKRelationState' {
            # a simple test to create an object
            #$NewObject = Initialize-OKRelationState
            #$NewObject | Should -BeOfType RelationState
            #$NewObject.property | Should -Be 0
        }
    }
}
