#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKRelatedCIDTO' {
    Context 'OKRelatedCIDTO' {
        It 'Initialize-OKRelatedCIDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKRelatedCIDTO -FromCIID "TEST_VALUE" -ToCIID "TEST_VALUE" -PredicateID "TEST_VALUE"
            #$NewObject | Should -BeOfType RelatedCIDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
