#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKRelationDTO' {
    Context 'OKRelationDTO' {
        It 'Initialize-OKRelationDTO' {
            # a simple test to create an object
            #$NewObject = Initialize-OKRelationDTO -Id "TEST_VALUE" -FromCIID "TEST_VALUE" -ToCIID "TEST_VALUE" -PredicateID "TEST_VALUE" -Predicate "TEST_VALUE" -State "TEST_VALUE"
            #$NewObject | Should -BeOfType RelationDTO
            #$NewObject.property | Should -Be 0
        }
    }
}
