#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKSameTempIDHandling' {
    Context 'OKSameTempIDHandling' {
        It 'Initialize-OKSameTempIDHandling' {
            # a simple test to create an object
            #$NewObject = Initialize-OKSameTempIDHandling
            #$NewObject | Should -BeOfType SameTempIDHandling
            #$NewObject.property | Should -Be 0
        }
    }
}
