#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKSameTargetCIHandling' {
    Context 'OKSameTargetCIHandling' {
        It 'Initialize-OKSameTargetCIHandling' {
            # a simple test to create an object
            #$NewObject = Initialize-OKSameTargetCIHandling
            #$NewObject | Should -BeOfType SameTargetCIHandling
            #$NewObject.property | Should -Be 0
        }
    }
}
