#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'okclient' -name 'OKSparseRow' {
    Context 'OKSparseRow' {
        It 'Initialize-OKSparseRow' {
            # a simple test to create an object
            #$NewObject = Initialize-OKSparseRow -Ciid "TEST_VALUE" -Cells "TEST_VALUE"
            #$NewObject | Should -BeOfType SparseRow
            #$NewObject.property | Should -Be 0
        }
    }
}
