#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum AttributeState.

.DESCRIPTION

No description available.
#>

enum AttributeState {
    # enum value: "New"
    New
    # enum value: "Changed"
    Changed
    # enum value: "Removed"
    Removed
    # enum value: "Renewed"
    Renewed
}

