#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SparseRows
No description available.
.OUTPUTS

ChangeDataRequest<PSCustomObject>
#>

function Initialize-OKChangeDataRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${SparseRows}
    )

    Process {
        'Creating PSCustomObject: okclient => OKChangeDataRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "sparseRows" = ${SparseRows}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ChangeDataRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to ChangeDataRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ChangeDataRequest<PSCustomObject>
#>
function ConvertFrom-OKJsonToChangeDataRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKChangeDataRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKChangeDataRequest
        $AllProperties = ("sparseRows")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sparseRows"))) { #optional property not found
            $SparseRows = $null
        } else {
            $SparseRows = $JsonParameters.PSobject.Properties["sparseRows"].value
        }

        $PSO = [PSCustomObject]@{
            "sparseRows" = ${SparseRows}
        }

        return $PSO
    }

}

