#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER ExtractConfig
No description available.
.PARAMETER TransformConfig
No description available.
.PARAMETER LoadConfig
No description available.
.OUTPUTS

Context<PSCustomObject>
#>

function Initialize-OKContext {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ExtractConfig},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TransformConfig},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${LoadConfig}
    )

    Process {
        'Creating PSCustomObject: okclient => OKContext' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "extractConfig" = ${ExtractConfig}
            "transformConfig" = ${TransformConfig}
            "loadConfig" = ${LoadConfig}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Context<PSCustomObject>

.DESCRIPTION

Convert from JSON to Context<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Context<PSCustomObject>
#>
function ConvertFrom-OKJsonToContext {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKContext' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKContext
        $AllProperties = ("id", "extractConfig", "transformConfig", "loadConfig")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extractConfig"))) { #optional property not found
            $ExtractConfig = $null
        } else {
            $ExtractConfig = $JsonParameters.PSobject.Properties["extractConfig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "transformConfig"))) { #optional property not found
            $TransformConfig = $null
        } else {
            $TransformConfig = $JsonParameters.PSobject.Properties["transformConfig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "loadConfig"))) { #optional property not found
            $LoadConfig = $null
        } else {
            $LoadConfig = $JsonParameters.PSobject.Properties["loadConfig"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "extractConfig" = ${ExtractConfig}
            "transformConfig" = ${TransformConfig}
            "loadConfig" = ${LoadConfig}
        }

        return $PSO
    }

}

