#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SpeakingName
No description available.
.PARAMETER Description
No description available.
.PARAMETER Configuration
No description available.
.OUTPUTS

EditContextRequest<PSCustomObject>
#>

function Initialize-OKEditContextRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SpeakingName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Configuration}
    )

    Process {
        'Creating PSCustomObject: okclient => OKEditContextRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "speakingName" = ${SpeakingName}
            "description" = ${Description}
            "configuration" = ${Configuration}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EditContextRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to EditContextRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EditContextRequest<PSCustomObject>
#>
function ConvertFrom-OKJsonToEditContextRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKEditContextRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKEditContextRequest
        $AllProperties = ("speakingName", "description", "configuration")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "speakingName"))) { #optional property not found
            $SpeakingName = $null
        } else {
            $SpeakingName = $JsonParameters.PSobject.Properties["speakingName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "configuration"))) { #optional property not found
            $Configuration = $null
        } else {
            $Configuration = $JsonParameters.PSobject.Properties["configuration"].value
        }

        $PSO = [PSCustomObject]@{
            "speakingName" = ${SpeakingName}
            "description" = ${Description}
            "configuration" = ${Configuration}
        }

        return $PSO
    }

}

