#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum EdmSchemaElementKind.

.DESCRIPTION

No description available.
#>

enum EdmSchemaElementKind {
    # enum value: "None"
    None
    # enum value: "TypeDefinition"
    TypeDefinition
    # enum value: "Term"
    Term
    # enum value: "Action"
    Action
    # enum value: "EntityContainer"
    EntityContainer
    # enum value: "Function"
    Function
}

