#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum EdmTypeKind.

.DESCRIPTION

No description available.
#>

enum EdmTypeKind {
    # enum value: "None"
    None
    # enum value: "Primitive"
    Primitive
    # enum value: "Entity"
    Entity
    # enum value: "Complex"
    Complex
    # enum value: "Collection"
    Collection
    # enum value: "EntityReference"
    EntityReference
    # enum value: "Enum"
    Enum
    # enum value: "TypeDefinition"
    TypeDefinition
    # enum value: "Untyped"
    Untyped
    # enum value: "Path"
    Path
}

