#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VarFrom
No description available.
.PARAMETER Predicate
No description available.
.PARAMETER To
No description available.
.OUTPUTS

GenericInboundRelation<PSCustomObject>
#>

function Initialize-OKGenericInboundRelation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarFrom},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Predicate},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${To}
    )

    Process {
        'Creating PSCustomObject: okclient => OKGenericInboundRelation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "from" = ${VarFrom}
            "predicate" = ${Predicate}
            "to" = ${To}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GenericInboundRelation<PSCustomObject>

.DESCRIPTION

Convert from JSON to GenericInboundRelation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GenericInboundRelation<PSCustomObject>
#>
function ConvertFrom-OKJsonToGenericInboundRelation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKGenericInboundRelation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKGenericInboundRelation
        $AllProperties = ("from", "predicate", "to")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "from"))) { #optional property not found
            $VarFrom = $null
        } else {
            $VarFrom = $JsonParameters.PSobject.Properties["from"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "predicate"))) { #optional property not found
            $Predicate = $null
        } else {
            $Predicate = $JsonParameters.PSobject.Properties["predicate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "to"))) { #optional property not found
            $To = $null
        } else {
            $To = $JsonParameters.PSobject.Properties["to"].value
        }

        $PSO = [PSCustomObject]@{
            "from" = ${VarFrom}
            "predicate" = ${Predicate}
            "to" = ${To}
        }

        return $PSO
    }

}

