#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Cis
No description available.
.PARAMETER Relations
No description available.
.OUTPUTS

GenericInboundData<PSCustomObject>
#>

function Initialize-OKGenericInboundData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Cis},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Relations}
    )

    Process {
        'Creating PSCustomObject: okclient => OKGenericInboundData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "cis" = ${Cis}
            "relations" = ${Relations}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GenericInboundData<PSCustomObject>

.DESCRIPTION

Convert from JSON to GenericInboundData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GenericInboundData<PSCustomObject>
#>
function ConvertFrom-OKJsonToGenericInboundData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKGenericInboundData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKGenericInboundData
        $AllProperties = ("cis", "relations")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cis"))) { #optional property not found
            $Cis = $null
        } else {
            $Cis = $JsonParameters.PSobject.Properties["cis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "relations"))) { #optional property not found
            $Relations = $null
        } else {
            $Relations = $JsonParameters.PSobject.Properties["relations"].value
        }

        $PSO = [PSCustomObject]@{
            "cis" = ${Cis}
            "relations" = ${Relations}
        }

        return $PSO
    }

}

