#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Qualifier
No description available.
.PARAMETER Term
No description available.
.PARAMETER Target
No description available.
.PARAMETER Value
No description available.
.OUTPUTS

IEdmVocabularyAnnotation<PSCustomObject>
#>

function Initialize-OKIEdmVocabularyAnnotation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Qualifier},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Term},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Target},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Value}
    )

    Process {
        'Creating PSCustomObject: okclient => OKIEdmVocabularyAnnotation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "qualifier" = ${Qualifier}
            "term" = ${Term}
            "target" = ${Target}
            "value" = ${Value}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IEdmVocabularyAnnotation<PSCustomObject>

.DESCRIPTION

Convert from JSON to IEdmVocabularyAnnotation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IEdmVocabularyAnnotation<PSCustomObject>
#>
function ConvertFrom-OKJsonToIEdmVocabularyAnnotation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKIEdmVocabularyAnnotation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKIEdmVocabularyAnnotation
        $AllProperties = ("qualifier", "term", "target", "value")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "qualifier"))) { #optional property not found
            $Qualifier = $null
        } else {
            $Qualifier = $JsonParameters.PSobject.Properties["qualifier"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "term"))) { #optional property not found
            $Term = $null
        } else {
            $Term = $JsonParameters.PSobject.Properties["term"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target"))) { #optional property not found
            $Target = $null
        } else {
            $Target = $JsonParameters.PSobject.Properties["target"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        $PSO = [PSCustomObject]@{
            "qualifier" = ${Qualifier}
            "term" = ${Term}
            "target" = ${Target}
            "value" = ${Value}
        }

        return $PSO
    }

}

