#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TypeKind
No description available.
.OUTPUTS

IEdmType<PSCustomObject>
#>

function Initialize-OKIEdmType {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TypeKind}
    )

    Process {
        'Creating PSCustomObject: okclient => OKIEdmType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "typeKind" = ${TypeKind}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IEdmType<PSCustomObject>

.DESCRIPTION

Convert from JSON to IEdmType<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IEdmType<PSCustomObject>
#>
function ConvertFrom-OKJsonToIEdmType {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKIEdmType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKIEdmType
        $AllProperties = ("typeKind")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "typeKind"))) { #optional property not found
            $TypeKind = $null
        } else {
            $TypeKind = $JsonParameters.PSobject.Properties["typeKind"].value
        }

        $PSO = [PSCustomObject]@{
            "typeKind" = ${TypeKind}
        }

        return $PSO
    }

}

