#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SearchLayerIDs
No description available.
.PARAMETER WriteLayerID
No description available.
.OUTPUTS

ILoadConfig<PSCustomObject>
#>

function Initialize-OKILoadConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${SearchLayerIDs},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WriteLayerID}
    )

    Process {
        'Creating PSCustomObject: okclient => OKILoadConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "searchLayerIDs" = ${SearchLayerIDs}
            "writeLayerID" = ${WriteLayerID}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ILoadConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to ILoadConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ILoadConfig<PSCustomObject>
#>
function ConvertFrom-OKJsonToILoadConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKILoadConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKILoadConfig
        $AllProperties = ("searchLayerIDs", "writeLayerID")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "searchLayerIDs"))) { #optional property not found
            $SearchLayerIDs = $null
        } else {
            $SearchLayerIDs = $JsonParameters.PSobject.Properties["searchLayerIDs"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "writeLayerID"))) { #optional property not found
            $WriteLayerID = $null
        } else {
            $WriteLayerID = $JsonParameters.PSobject.Properties["writeLayerID"].value
        }

        $PSO = [PSCustomObject]@{
            "searchLayerIDs" = ${SearchLayerIDs}
            "writeLayerID" = ${WriteLayerID}
        }

        return $PSO
    }

}

