#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Type
No description available.
.PARAMETER Attribute
No description available.
.PARAMETER Modifiers
No description available.
.OUTPUTS

InboundIDMethodByAttribute<PSCustomObject>
#>

function Initialize-OKInboundIDMethodByAttribute {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Attribute},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Modifiers}
    )

    Process {
        'Creating PSCustomObject: okclient => OKInboundIDMethodByAttribute' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "attribute" = ${Attribute}
            "modifiers" = ${Modifiers}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to InboundIDMethodByAttribute<PSCustomObject>

.DESCRIPTION

Convert from JSON to InboundIDMethodByAttribute<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

InboundIDMethodByAttribute<PSCustomObject>
#>
function ConvertFrom-OKJsonToInboundIDMethodByAttribute {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKInboundIDMethodByAttribute' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKInboundIDMethodByAttribute
        $AllProperties = ("type", "attribute", "modifiers")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attribute"))) { #optional property not found
            $Attribute = $null
        } else {
            $Attribute = $JsonParameters.PSobject.Properties["attribute"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "modifiers"))) { #optional property not found
            $Modifiers = $null
        } else {
            $Modifiers = $JsonParameters.PSobject.Properties["modifiers"].value
        }

        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "attribute" = ${Attribute}
            "modifiers" = ${Modifiers}
        }

        return $PSO
    }

}

