#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum NoFoundTargetCIHandling.

.DESCRIPTION

No description available.
#>

enum NoFoundTargetCIHandling {
    # enum value: "CreateNew"
    CreateNew
    # enum value: "CreateNewAndWarn"
    CreateNewAndWarn
    # enum value: "Drop"
    Drop
}

