#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TypeAnnotation
No description available.
.PARAMETER Url
No description available.
.PARAMETER Name
No description available.
.PARAMETER Title
No description available.
.OUTPUTS

ODataSingletonInfo<PSCustomObject>
#>

function Initialize-OKODataSingletonInfo {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TypeAnnotation},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title}
    )

    Process {
        'Creating PSCustomObject: okclient => OKODataSingletonInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "typeAnnotation" = ${TypeAnnotation}
            "url" = ${Url}
            "name" = ${Name}
            "title" = ${Title}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ODataSingletonInfo<PSCustomObject>

.DESCRIPTION

Convert from JSON to ODataSingletonInfo<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ODataSingletonInfo<PSCustomObject>
#>
function ConvertFrom-OKJsonToODataSingletonInfo {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKODataSingletonInfo' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKODataSingletonInfo
        $AllProperties = ("typeAnnotation", "url", "name", "title")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "typeAnnotation"))) { #optional property not found
            $TypeAnnotation = $null
        } else {
            $TypeAnnotation = $JsonParameters.PSobject.Properties["typeAnnotation"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        $PSO = [PSCustomObject]@{
            "typeAnnotation" = ${TypeAnnotation}
            "url" = ${Url}
            "name" = ${Name}
            "title" = ${Title}
        }

        return $PSO
    }

}

