#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TypeName
No description available.
.OUTPUTS

ODataTypeAnnotation<PSCustomObject>
#>

function Initialize-OKODataTypeAnnotation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TypeName}
    )

    Process {
        'Creating PSCustomObject: okclient => OKODataTypeAnnotation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "typeName" = ${TypeName}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ODataTypeAnnotation<PSCustomObject>

.DESCRIPTION

Convert from JSON to ODataTypeAnnotation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ODataTypeAnnotation<PSCustomObject>
#>
function ConvertFrom-OKJsonToODataTypeAnnotation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: okclient => OKODataTypeAnnotation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OKODataTypeAnnotation
        $AllProperties = ("typeName")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "typeName"))) { #optional property not found
            $TypeName = $null
        } else {
            $TypeName = $JsonParameters.PSobject.Properties["typeName"].value
        }

        $PSO = [PSCustomObject]@{
            "typeName" = ${TypeName}
        }

        return $PSO
    }

}

