#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum SameTempIDHandling.

.DESCRIPTION

No description available.
#>

enum SameTempIDHandling {
    # enum value: "DropAndWarn"
    DropAndWarn
    # enum value: "Drop"
    Drop
}

