#
# Landscape omnikeeper REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum SameTargetCIHandling.

.DESCRIPTION

No description available.
#>

enum SameTargetCIHandling {
    # enum value: "Error"
    Error
    # enum value: "Drop"
    Drop
    # enum value: "DropAndWarn"
    DropAndWarn
    # enum value: "Evade"
    Evade
    # enum value: "EvadeAndWarn"
    EvadeAndWarn
    # enum value: "Merge"
    Merge
}

